version: '3'

services:
  reactjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: dreamsociety-reactjs
    container_name: dreamsociety-reactjs
    restart: unless-stopped 
    ports:
      - "3001:3000"
      - "3002:3000"
    volumes:
      - .:/dreamSociety-FE/app
      - node_modules:/dreamSociety-FE/app/node_modules
    networks:
      - app-network
    command: yarn start

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
